version: "3.7"
services:
  tyk-gateway:
    container_name: tyk-gateway
    image: tykio/tyk-gateway:v2.9.2
    depends_on:
      - redis-for-tyk-gateway
      - grpc-for-tyk-gateway
    ports:
      - "30100:8080"
    volumes:
      - "./tyk.conf:/opt/tyk-gateway/tyk.conf"
    environment:
      - "TYK_GW_SECRET=5830f19dee9b799d89719d2cd62baf09"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  redis-for-tyk-gateway:
    container_name: redis-for-tyk-gateway
    image: redis:5.0.7
    ports:
      - "30101:6379"
    volumes:
      - "redis_tyk_data:/data"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  grpc-for-tyk-gateway:
    container_name: grpc-for-tyk-gateway
    image: grpc-server:latest
    ports:
      - "30102:8090"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
volumes:
  redis_tyk_data:
networks:
  tyk:
