version: "3.7"
services:
  tyk-gateway:
    container_name: tyk-gateway
    image: tykio/tyk-gateway:v2.9.2
    depends_on:
      - redis-server
    ports:
      - "30100:8080"
    volumes:
      - "./tyk.conf:/opt/tyk-gateway/tyk.conf"
      - "./tyk-gateway-apis:/opt/tyk-gateway/apps"
      - "./nginx-root:/outside"
    environment:
      - "TYK_GW_SECRET=5830f19dee9b799d89719d2cd62baf09"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  redis-server:
    container_name: redis-server
    image: redis:5.0.7
    ports:
      - "30101:6379"
    volumes:
      - "redis_tyk_data:/data"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  bundle-server:
    container_name: bundle-server
    image: nginx:1.17.6
    ports:
      - "30103:80"
    volumes:
      - "./nginx-root:/usr/share/nginx/html:ro"
    restart: on-failure
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  grpc-server:
    container_name: grpc-server
    build: ./java-8-runtime
    image: java-8-runtime:latest
    ports:
      - "30104:80"
    restart: on-failure
    volumes:
      - "./servers:/opt/java/jar"
    command: "-Dport=80 grpc-server.jar"
    networks:
      - tyk
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
volumes:
  redis_tyk_data:
networks:
  tyk:
